# Site settings
title: ZYMBROS.
email: gbrs.dev@gmail.com
url: https://gbrs.netlify.app/
description: "ZYMBROS. is a Personalized AI Fitness Trainer that helps you achieve your fitness goals."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#B20710'

# Footer settings
footer: ZYMBROS.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: https://twitter.com/SBootstrap
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  - title: blog
    url: https://gbrsblog.netlify.app/
  - title: github
    url: https://github.com/notj-code/GYMBROS
# Build settings
markdown: kramdown
permalink: pretty
